# Generated by Django 5.2.5 on 2025-08-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='playlist_url',
            field=models.URLField(blank=True, help_text='ضع رابط بلاي ليست من يوتيوب', null=True),
        ),
    ]
