# Generated by Django 5.2.4 on 2025-08-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_playlist_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='playlist_url',
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='حط رابط الفيديو هنا', null=True),
        ),
    ]
