# Generated by Django 5.2.4 on 2025-08-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_playlist_url_course_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='video_url',
            new_name='playlist_url',
        ),
    ]
