# Generated by Django 5.2.4 on 2025-08-21 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_video_url_course_playlist_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='playlist_url',
            new_name='video_url',
        ),
    ]
